// This file will be auto-generated by Supabase CLI
// For now, using a basic placeholder

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string | null;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          username?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          username?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      game_stats: {
        Row: {
          id: string;
          user_id: string;
          game_type: string;
          games_played: number;
          games_won: number;
          games_lost: number;
          games_draw: number;
          win_streak: number;
          best_win_streak: number;
          total_play_time: number;
          by_opponent: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          game_type: string;
          games_played?: number;
          games_won?: number;
          games_lost?: number;
          games_draw?: number;
          win_streak?: number;
          best_win_streak?: number;
          total_play_time?: number;
          by_opponent?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          game_type?: string;
          games_played?: number;
          games_won?: number;
          games_lost?: number;
          games_draw?: number;
          win_streak?: number;
          best_win_streak?: number;
          total_play_time?: number;
          by_opponent?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      game_rooms: {
        Row: {
          id: string;
          game_type: string;
          status: string;
          player1_id: string | null;
          player2_id: string | null;
          current_turn: string | null;
          board: string[] | null;
          winner_id: string | null;
          is_draw: boolean;
          is_private: boolean;
          rematch_requested_by: string | null;
          rematch_room_id: string | null;
          metadata: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          game_type: string;
          status?: string;
          player1_id?: string | null;
          player2_id?: string | null;
          current_turn?: string | null;
          board?: string[] | null;
          winner_id?: string | null;
          is_draw?: boolean;
          is_private?: boolean;
          rematch_requested_by?: string | null;
          rematch_room_id?: string | null;
          metadata?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          game_type?: string;
          status?: string;
          player1_id?: string | null;
          player2_id?: string | null;
          current_turn?: string | null;
          board?: string[] | null;
          winner_id?: string | null;
          is_draw?: boolean;
          is_private?: boolean;
          rematch_requested_by?: string | null;
          rematch_room_id?: string | null;
          metadata?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      wallets: {
        Row: {
          id: string;
          user_id: string;
          balance: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          balance?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          balance?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      wallet_transactions: {
        Row: {
          id: string;
          wallet_id: string;
          type: string;
          amount: number;
          balance_after: number;
          description: string | null;
          game_slug: string | null;
          metadata: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          wallet_id: string;
          type: string;
          amount: number;
          balance_after: number;
          description?: string | null;
          game_slug?: string | null;
          metadata?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          wallet_id?: string;
          type?: string;
          amount?: number;
          balance_after?: number;
          description?: string | null;
          game_slug?: string | null;
          metadata?: Json | null;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    // NOTE: RPC functions are defined in Supabase but types require CLI regeneration
    // Run `supabase gen types typescript` to update these
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}

// Helper types
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];
export type InsertTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];
export type UpdateTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];

// Convenience types
export type Profile = Tables<'profiles'>;
export type GameStats = Tables<'game_stats'>;
export type GameRoom = Tables<'game_rooms'>;
export type Wallet = Tables<'wallets'>;
export type WalletTransaction = Tables<'wallet_transactions'>;
